//
//  DishDetailViewController.swift
//  FoodDelivery
//
//  Created by fhasni on 11/18/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class DishDetailViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: DishDetailPresenterInterface!

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

}

// MARK: - Extensions -

extension DishDetailViewController: DishDetailViewInterface {
}

private extension DishDetailViewController {

    func setupView() {
        let output = DishDetail.ViewOutput()

        let input = presenter.configure(with: output)
    }

}
