//
//  DishDetailFormatter.swift
//  FoodDelivery
//
//  Created by fhasni on 11/18/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class DishDetailFormatter {
}

// MARK: - Extensions -

extension DishDetailFormatter: DishDetailFormatterInterface {

    func format(for input: DishDetail.FormatterInput) -> DishDetail.FormatterOutput {
        return DishDetail.FormatterOutput()
    }

}
