//
//  DishDetailWireframe.swift
//  FoodDelivery
//
//  Created by fhasni on 11/18/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class DishDetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "DishDetail", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: DishDetailViewController.self)
        super.init(viewController: moduleViewController)

        let formatter = DishDetailFormatter()
        let interactor = DishDetailInteractor()
        let presenter = DishDetailPresenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DishDetailWireframe: DishDetailWireframeInterface {
}
