//
//  DishDetailInteractor.swift
//  FoodDelivery
//
//  Created by fhasni on 11/18/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class DishDetailInteractor {
}

// MARK: - Extensions -

extension DishDetailInteractor: DishDetailInteractorInterface {
}
