//
//  CheckoutViewController.swift
//  FoodDelivery
//
//  Created by fhasni on 11/18/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class CheckoutViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: CheckoutPresenterInterface!

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

}

// MARK: - Extensions -

extension CheckoutViewController: CheckoutViewInterface {
}

private extension CheckoutViewController {

    func setupView() {
        let output = Checkout.ViewOutput()

        let input = presenter.configure(with: output)
    }

}
