//
//  CheckoutFormatter.swift
//  FoodDelivery
//
//  Created by fhasni on 11/18/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class CheckoutFormatter {
}

// MARK: - Extensions -

extension CheckoutFormatter: CheckoutFormatterInterface {

    func format(for input: Checkout.FormatterInput) -> Checkout.FormatterOutput {
        return Checkout.FormatterOutput()
    }

}
