//
//  HomeInterfaces.swift
//  FoodDelivery
//
//  Created by fhasni on 10/29/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import RxSwift

protocol HomeWireframeInterface: WireframeInterface {
}

protocol HomeViewInterface: ViewInterface {
}

protocol HomePresenterInterface: PresenterInterface {
    func configure(with output: Home.ViewOutput) -> Home.ViewInput
}

protocol HomeFormatterInterface: FormatterInterface {
    func format(for input: Home.FormatterInput) -> Home.FormatterOutput
}

protocol HomeInteractorInterface: InteractorInterface {
    var menu : Single<Menu?> { get }
}

enum Home {

    struct ViewOutput {
    }

    struct ViewInput {
        let models: FormatterOutput
        let menu: Single<Menu?>
    }

    struct FormatterInput {
    }

    struct FormatterOutput {
    }

}
