//
//  RestaurentDetailsInterfaces.swift
//  FoodDelivery
//
//  Created by fhasni on 10/29/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import RxSwift

protocol RestaurentDetailsWireframeInterface: WireframeInterface {
}

protocol RestaurentDetailsViewInterface: ViewInterface {
}

protocol RestaurentDetailsPresenterInterface: PresenterInterface {
    func configure(with output: RestaurentDetails.ViewOutput) -> RestaurentDetails.ViewInput
}

protocol RestaurentDetailsFormatterInterface: FormatterInterface {
    func format(for input: RestaurentDetails.FormatterInput) -> RestaurentDetails.FormatterOutput
}

protocol RestaurentDetailsInteractorInterface: InteractorInterface {
}

enum RestaurentDetails {

    struct ViewOutput {
    }

    struct ViewInput {
        let models: FormatterOutput
    }

    struct FormatterInput {
    }

    struct FormatterOutput {
    }

}
