//
//  RestaurentDetailsViewController.swift
//  FoodDelivery
//
//  Created by fhasni on 10/29/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class RestaurentDetailsViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: RestaurentDetailsPresenterInterface!

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }

}

// MARK: - Extensions -

extension RestaurentDetailsViewController: RestaurentDetailsViewInterface {
}

private extension RestaurentDetailsViewController {

    func setupView() {
        let output = RestaurentDetails.ViewOutput()

        let input = presenter.configure(with: output)
    }

}
