//
//  RestaurentDetailsWireframe.swift
//  FoodDelivery
//
//  Created by fhasni on 10/29/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class RestaurentDetailsWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "RestaurentDetails", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = storyboard.instantiateViewController(ofType: RestaurentDetailsViewController.self)
        super.init(viewController: moduleViewController)

        let formatter = RestaurentDetailsFormatter()
        let interactor = RestaurentDetailsInteractor()
        let presenter = RestaurentDetailsPresenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension RestaurentDetailsWireframe: RestaurentDetailsWireframeInterface {
}
