//
//  RestaurentDetailsPresenter.swift
//  FoodDelivery
//
//  Created by fhasni on 10/29/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class RestaurentDetailsPresenter {

    // MARK: - Private properties -

    private unowned let view: RestaurentDetailsViewInterface
    private let formatter: RestaurentDetailsFormatterInterface
    private let interactor: RestaurentDetailsInteractorInterface
    private let wireframe: RestaurentDetailsWireframeInterface

    // MARK: - Lifecycle -

    init(view: RestaurentDetailsViewInterface, formatter: RestaurentDetailsFormatterInterface, interactor: RestaurentDetailsInteractorInterface, wireframe: RestaurentDetailsWireframeInterface) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension RestaurentDetailsPresenter: RestaurentDetailsPresenterInterface {

    func configure(with output: RestaurentDetails.ViewOutput) -> RestaurentDetails.ViewInput {

        let formatterInput = RestaurentDetails.FormatterInput()

        let formatterOutput = formatter.format(for: formatterInput)

        return RestaurentDetails.ViewInput(models: formatterOutput)
    }

}
