//
//  RestaurentDetailsFormatter.swift
//  FoodDelivery
//
//  Created by fhasni on 10/29/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class RestaurentDetailsFormatter {
}

// MARK: - Extensions -

extension RestaurentDetailsFormatter: RestaurentDetailsFormatterInterface {

    func format(for input: RestaurentDetails.FormatterInput) -> RestaurentDetails.FormatterOutput {
        return RestaurentDetails.FormatterOutput()
    }

}
