//
//  CartFormatter.swift
//  FoodDelivery
//
//  Created by fhasni on 11/8/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class CartFormatter {
}

// MARK: - Extensions -

extension CartFormatter: CartFormatterInterface {

    func format(for input: Cart.FormatterInput) -> Cart.FormatterOutput {
        return Cart.FormatterOutput()
    }

}
