//
//  CartInteractor.swift
//  FoodDelivery
//
//  Created by fhasni on 11/8/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class CartInteractor {
    private let cartRepositoty: CartRepositoryInterface
    
    init(cartRepositoty: CartRepositoryInterface) {
        self.cartRepositoty = cartRepositoty
    }
}

// MARK: - Extensions -

extension CartInteractor: CartInteractorInterface {
    
    func getCartItems() -> Observable<[CartItem]> {
        return cartRepositoty.getItems().map { (dishes) -> [CartItem] in
            Dictionary(grouping: dishes) { $0.id }
                .map {  CartItem(dish: $1[0], count: $1.count) }
        }
    }
    
}
