//
//  CartPresenter.swift
//  FoodDelivery
//
//  Created by fhasni on 11/8/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift
import RxCocoa

final class CartPresenter {

    // MARK: - Private properties -

    private unowned let view: CartViewInterface
    private let formatter: CartFormatterInterface
    private let interactor: CartInteractorInterface
    private let wireframe: CartWireframeInterface

    // MARK: - Lifecycle -

    init(view: CartViewInterface, formatter: CartFormatterInterface, interactor: CartInteractorInterface, wireframe: CartWireframeInterface) {
        self.view = view
        self.formatter = formatter
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension CartPresenter: CartPresenterInterface {

    func configure(with output: Cart.ViewOutput) -> Cart.ViewInput {

        let formatterInput = Cart.FormatterInput()

        let formatterOutput = formatter.format(for: formatterInput)

        return Cart.ViewInput(models: formatterOutput, cartItems: interactor.getCartItems().asDriver(onErrorJustReturn: []))
    }

}
