//
//  CartViewController.swift
//  FoodDelivery
//
//  Created by fhasni on 11/8/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa


final class CartViewController: UIViewController {
    
    // MARK: - Public properties -
    
    var presenter: CartPresenterInterface!
    
    // MARK: - Private properties -
    
    private let cartTableView: UITableView = {
        let tableView = UITableView()
        tableView.register(CartItemCell.self, forCellReuseIdentifier: CartItemCell.reuseIdentifier)
        tableView.rowHeight = 200
        tableView.separatorStyle = .none
        tableView.allowsSelection = false
        tableView.showsVerticalScrollIndicator = false
        tableView.tableFooterView = UIView()
        return tableView
    }()
    
    private let disposeBag = DisposeBag()
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupRx()
        setupUI()
    }
    
}

// MARK: - Extensions -

extension CartViewController: CartViewInterface {
}

private extension CartViewController {
    
    func setupRx() {
        let output = Cart.ViewOutput()
        
        let input = presenter.configure(with: output)
        
        input.cartItems
        .drive(cartTableView.rx.items(cellIdentifier: CartItemCell.reuseIdentifier, cellType: CartItemCell.self)) { (row, cartItem, cell) in
            cell.cartItem = cartItem
        }
        .disposed(by: disposeBag)
    }
    
    func setupUI() {
        setupNavigationBar()
//        setupTableView()
        view.addSubview(cartTableView)
        cartTableView.snp.makeConstraints { (make) in
            make.edges.equalTo(view)
        }
    }
    
    
    func setupNavigationBar() {
        configureNavigationbar(withTitle: "Cart",
                               prefersLargeTitles: true)
        
        
        self.navigationItem.leftBarButtonItem = UIBarButtonItem(customView: {
                                                    let button = UIButton(type: .custom)
                                                    button.tintColor = .black
                                                    button.setImage(UIImage(systemName: "chevron.left") , for: .normal)
                                                    button.setTitle("Menu", for: .normal)
                                                    button.setTitleColor(button.tintColor, for: .normal)
                                                    button.addTarget(self, action: #selector(backClicked), for: .touchUpInside)
                                                    return button
                                                }())
    }
    
//    func setupTableView() {
////        cartTableView.delegate = self
////        cartTableView.dataSource = self
//
//        cartTableView.register(CartItemCell.self, forCellReuseIdentifier: CartItemCell.reuseIdentifier)
//        cartTableView.rowHeight = 200
//        cartTableView.separatorStyle = .none
//        cartTableView.allowsSelection = false
//        cartTableView.showsVerticalScrollIndicator = false
//    }
    
    @objc func backClicked() -> Void {
       self.navigationController?.dismiss(animated: true)
    }
}

//extension CartViewController : UITableViewDelegate, UITableViewDataSource {
//    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
//        return 10
//    }
//
//    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
//        let cell = tableView.dequeueReusableCell(withIdentifier: CartItemCell.reuseIdentifier, for: indexPath) as! CartItemCell
//        let dish = Dish(id: "", name: "Seafood Sauté or Alfredo", price: 19.5, image: "https://bit.ly/35yh09N", description: "")
//        cell.cartItem = CartItem(dish:dish, count: 1)
//        return cell
//    }
//}
