//
//  CartViewController.swift
//  FoodDelivery
//
//  Created by fhasni on 11/8/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class CartViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: CartPresenterInterface!

    // MARK: - Private properties -

    private let disposeBag = DisposeBag()

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupRx()
    }

}

// MARK: - Extensions -

extension CartViewController: CartViewInterface {
}

private extension CartViewController {

    func setupRx() {
        let output = Cart.ViewOutput()

        let _ = presenter.configure(with: output)
    }

}
