//
//  RestaurentDetailsInteractor.swift
//  FoodDelivery
//
//  Created by fhasni on 10/29/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class RestaurentDetailsInteractor {
}

// MARK: - Extensions -

extension RestaurentDetailsInteractor: RestaurentDetailsInteractorInterface {
}
