//
//  HomeInterfaces.swift
//  FoodDelivery
//
//  Created by fhasni on 10/24/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

protocol HomeWireframeInterface: WireframeInterface {
}

protocol HomeViewInterface: ViewInterface {
}

protocol HomePresenterInterface: PresenterInterface {
    func configure(with output: Home.ViewOutput) -> Home.ViewInput
}

enum Home {

    struct ViewOutput {
    }

    struct ViewInput {
    }

}
