//
//  HomeFormatter.swift
//  FoodDelivery
//
//  Created by fhasni on 10/29/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class HomeFormatter {
}

// MARK: - Extensions -

extension HomeFormatter: HomeFormatterInterface {

    func format(for input: Home.FormatterInput) -> Home.FormatterOutput {
        return Home.FormatterOutput()
    }

}
