//
//  HomeViewController.swift
//  FoodDelivery
//
//  Created by fhasni on 10/29/20.
//  Copyright (c) 2020 fhasni. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class HomeViewController: UIViewController {
    
    // MARK: - Public properties -
    
    var presenter: HomePresenterInterface!
    
    // MARK: - Private properties -
    
    private lazy var promotionsView: PromotionsView = {
        let view = PromotionsView()
        view.presenter = self.presenter
        return view
    }()
    
    private lazy var foodMenuView : FoodMenuView = {
        let view = FoodMenuView(presenter: presenter)
        view.presenter = self.presenter
        return view
    }()
    
    private let disposeBag = DisposeBag()
    
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
    
}

// MARK: - Extensions -

extension HomeViewController: HomeViewInterface {
}

private extension HomeViewController {
    
    func setupView() {
        let output = Home.ViewOutput()
        _ = presenter.configure(with: output)
        configureUI()
    }
    
    func configureUI() {
        configureNavigationBar()
        
        view.addSubview(promotionsView)
        promotionsView.anchor(top: view.topAnchor, left: view.leftAnchor,
                              right: view.rightAnchor, height: 22+55+700)
                
        view.addSubview(foodMenuView)
        foodMenuView.anchor(top: view.topAnchor, left: view.leftAnchor,
                            bottom: view.bottomAnchor, right: view.rightAnchor)
    }
    
    func configureNavigationBar() {
        navigationController?.navigationBar.isHidden = true
        navigationController?.navigationBar.barStyle = .black
    }
}
